/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package diplomski;
import java.io.File;
import java.io.RandomAccessFile;
import java.io.IOException;
import diplomski.GetData;
import java.math.*;
import java.text.*;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Iterator;

import java.awt.Graphics;
import java.awt.image.BufferedImage;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import org.jfree.chart.demo.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import org.jfree.ui.ApplicationFrame;
import org.jfree.ui.RefineryUtilities;

import diplomski.Ploter;
import java.awt.Color;

/**
 *
 * @author hrvoje
 */
public class Karta extends javax.swing.JFrame {

    /**
     * Creates new form Karta
     */

    public Karta() {
        initComponents();
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
    }
    private double distance(double lat1, double lon1, double lat2, double lon2) {
          double theta = lon1 - lon2;
            double dist = Math.sin(deg2rad(lat1)) * Math.sin(deg2rad(lat2)) + Math.cos(deg2rad(lat1)) * Math.cos(deg2rad(lat2)) * Math.cos(deg2rad(theta));
            dist = Math.acos(dist);
            dist = rad2deg(dist);
            dist = dist * 60 * 1.1515;
            dist = dist * 1.609344;
            return dist;
    }
    private double deg2rad(double deg) {
        return (deg * Math.PI / 180.0);
    }
    private double rad2deg(double rad) {
        return (rad * 180.0 / Math.PI);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Prepreka");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("LOS prepreka na:");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel6.setText("Visina terena 2");

        jLabel5.setText("Visina terena 1:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 48, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton2)
                .addGap(29, 29, 29))
        );

        jButton3.setText("Proracun terena");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Frekvencija [GHz]");

        jLabel11.setText("Gladak teren");

        jLabel12.setText("Neravan teren");

        jLabel13.setText("Postoji LOS");

        jLabel14.setText("Ne postoji LOS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel4.setText("Latitude 2:");

        jLabel9.setText("Visina Tx");

        jLabel10.setText("Visina Rx");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Longitude 2:");

        jButton1.setText("Racunaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Latitude 1:");

        jLabel1.setText("Longitude1:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(jTextField3)
                            .addComponent(jTextField1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jTextField4)
                            .addComponent(jTextField10)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jButton1)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(104, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(402, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data", jPanel4);

        jButton4.setText("Rezultati");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 943, Short.MAX_VALUE)
        );

        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setVisible(true);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diplomski/resources/difraction_over_horizon.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diplomski/resources/linear_interpolation.png"))); // NOI18N

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jInternalFrame1);
        try {
            jInternalFrame1.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(869, 869, 869)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(472, 472, 472)
                        .addComponent(jButton4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1163, 1163, 1163)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rezultati", jPanel5);

        jButton5.setText("Iscrtaj teren i LOS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Exportaj teren");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Iscrtaj Fresnel");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Export Fresnel");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jButton5))
                .addGap(438, 438, 438))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(479, 479, 479)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(jButton6))
                .addContainerGap(462, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(53, 53, 53)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addContainerGap(577, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Plot/Export", jPanel7);

        jMenu1.setText("File");

        jMenuItem1.setText("Izlaz");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Opcije");

        jMenuItem2.setText("Export teren");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Export Fresnel");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String duz1=jTextField1.getText();
            String sir1=jTextField2.getText();
            String duz2=jTextField3.getText();
            String sir2=jTextField4.getText();
            String put="C:\\Users\\vhailor\\Documents\\NetBeansProjects\\JavaApplication10\\";
            DecimalFormat f = new DecimalFormat("##");
            
            double du1=Double.valueOf(duz1);
            double si1=Double.valueOf(sir1);
            double du2=Double.valueOf(duz2);
            double si2=Double.valueOf(sir2);
            String d1=String.valueOf(f.format(Math.floor(du1)));
            String s1=String.valueOf(f.format(Math.floor(si1)));
            String d2=String.valueOf(f.format(Math.floor(du2)));
            String s2=String.valueOf(f.format(Math.floor(si2)));
            
            
            String nazivDat="";
            nazivDat+=put+"N"+d1+"E";
            if(si1<100) nazivDat+="0";
            nazivDat+=s1+".hgt";
            //File file = new File("C:\\Users\\vhailor\\Documents\\NetBeansProjects\\JavaApplication10\\N40E014.hgt");
            File file = new File(nazivDat);
            try{
                RandomAccessFile raf = new RandomAccessFile(file, "rw");
                RandomAccessFile raf2 = new RandomAccessFile(file, "rw");
                GetData dat=new GetData(raf);
                GetData dat2=new GetData(raf);
                double rez,rez2;
                rez=dat.getElevationFor(du1, si1);
                rez2=dat2.getElevationFor(du2, si2);
                jTextField5.setText(String.valueOf(rez));
                jTextField6.setText(String.valueOf(rez2));
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            String duz1=jTextField1.getText();
            String sir1=jTextField2.getText();
            String duz2=jTextField3.getText();
            String sir2=jTextField4.getText();
            String v1=jTextField9.getText();
            String v2=jTextField10.getText();
            float visAnt1=Float.valueOf(v1);
            float visAnt2=Float.valueOf(v2);
            String put="C:\\Users\\vhailor\\Documents\\NetBeansProjects\\JavaApplication10\\";
            DecimalFormat f = new DecimalFormat("##");
            DecimalFormat f1 = new DecimalFormat("##.##");
            
            
            double du1=Double.valueOf(duz1);
            double si1=Double.valueOf(sir1);
            double du2=Double.valueOf(duz2);
            double si2=Double.valueOf(sir2);
            String d1=String.valueOf(f.format(Math.floor(du1)));
            String s1=String.valueOf(f.format(Math.floor(si1)));
            String d2=String.valueOf(f.format(Math.floor(du2)));
            String s2=String.valueOf(f.format(Math.floor(si2)));
            double duljinaTrase=distance(du1,si1,du2,si2);
            int brUzoraka=10000;
            
            String nazivDat="";
            nazivDat+=put+"N"+d1+"E";
            if(si1<100) nazivDat+="0";
            nazivDat+=s1+".hgt";
            //File file = new File("C:\\Users\\vhailor\\Documents\\NetBeansProjects\\JavaApplication10\\N40E014.hgt");
            File file = new File(nazivDat);
            try{
                RandomAccessFile raf = new RandomAccessFile(file, "rw");
               
                GetData dat=new GetData(raf);
                double rez,rezLos,rez1,rezPoc,razT;
                int count=0;
                double razX=0,razY=0;
                boolean los=true;
                rezLos=Math.abs((dat.getElevationFor(du1, si1)+visAnt1)-(dat.getElevationFor(du2, si2)+visAnt2));//razlika najmanja najvisa tocka
                rezPoc=dat.getElevationFor(du1, si1)+visAnt1;
                ArrayList lista1=new ArrayList();
                while(count<=brUzoraka){
                    count++;
                    razX=Math.abs(du1-du2)/brUzoraka;
                    razY=Math.abs(si1-si2)/brUzoraka;
                    razT=duljinaTrase/brUzoraka;
                    rez=dat.getElevationFor(du1+(razX*count), si1+(razY*count));
                    rez1=rezPoc+(count*rezLos/brUzoraka);
                    lista1.add(rez1);
                    if(rez>rez1) {
                        los=false;
                        break;
                    }
                    
                }
                Iterator it=lista1.iterator();
                System.out.println(lista1.size());
               /* while(it.hasNext()){
                    System.out.print(it.next()+"\n");
                }*/
                if(los){
                    jTextField7.setText("Postoji LOS");
                    jLabel13.setVisible(true);
                    jLabel14.setVisible(false);
                } else {
                    String prep="";
                    prep+="N"+String.valueOf(f1.format(du1+razX))+"E"+String.valueOf(f1.format(si1+razY));
                    jTextField7.setText(prep);
                    jLabel14.setVisible(true);
                    jLabel13.setVisible(false);
                }

            }
            catch(IOException e){
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            String frek=jTextField8.getText();
            String put="C:\\Users\\vhailor\\Documents\\NetBeansProjects\\JavaApplication10\\";
            DecimalFormat f = new DecimalFormat("##");
            DecimalFormat f1 = new DecimalFormat("##.##");
            String duz1=jTextField1.getText();
            String sir1=jTextField2.getText();
            String duz2=jTextField3.getText();
            String sir2=jTextField4.getText();
            String v1=jTextField9.getText();
            String v2=jTextField10.getText();
            float visAnt1=Float.valueOf(v1);
            float visAnt2=Float.valueOf(v2);
            double du1=Double.valueOf(duz1);
            double si1=Double.valueOf(sir1);
            double du2=Double.valueOf(duz2);
            double si2=Double.valueOf(sir2);
            float antVis1=Float.valueOf(jTextField9.getText());
            float antVis2=Float.valueOf(jTextField10.getText());
            String d1=String.valueOf(f.format(Math.floor(du1)));
            String s1=String.valueOf(f.format(Math.floor(si1)));
            String d2=String.valueOf(f.format(Math.floor(du2)));
            String s2=String.valueOf(f.format(Math.floor(si2)));
            
            
            String nazivDat="";
            nazivDat+=put+"N"+d1+"E";
            if(si1<100) nazivDat+="0";
            nazivDat+=s1+".hgt";
            //File file = new File("C:\\Users\\vhailor\\Documents\\NetBeansProjects\\JavaApplication10\\N40E014.hgt");
            File file = new File(nazivDat);
            try{
                RandomAccessFile raf = new RandomAccessFile(file, "rw");
                GetData dat=new GetData(raf);
                int broj=0;
                double udaljenost=Math.abs(distance(du1,si1,du2,si2));
                double max=0;//MAX fresnel
                double maxFres=0;
                double fresnel,fresnelPlot;
                double rez,rezLos,rez1,rezPoc,rezKraj;
                int count=0;
                double razX=0,razY=0,razT;
                double dista1,dista2;
                double lambda=0.3/Double.parseDouble(frek);//frek u GHz --> lambda u m !!!!!!!!!!!
                double duljinaTrase=distance(du1,si1,du2,si2);
                int brUzoraka=10000;
                rezPoc=dat.getElevationFor(du1, si1)+visAnt1;
                rezKraj=dat.getElevationFor(du2, si2)+visAnt2;
                rezLos=Math.abs((dat.getElevationFor(du1, si1)+visAnt1)-(dat.getElevationFor(du2, si2)+visAnt2));
                
                while(count<=brUzoraka){
                    
                    razX=Math.abs(du1-du2)/brUzoraka;
                    razY=Math.abs(si1-si2)/brUzoraka;
                    razT=duljinaTrase/brUzoraka;
                    rez=dat.getElevationFor(du1+(razX*count), si1+(razY*count));

                    dista1=Math.abs(distance(du1,si1,du1+(razX*count),si1+(razY*count)));
                    dista2=Math.abs(distance(du2,si2,du1+(razX*count),si1+(razY*count)));
                    fresnel=1000*Math.sqrt((dista1*dista2*(lambda/1000))/(udaljenost));//fresnel radius 
                    if(fresnel>maxFres){
                        maxFres=fresnel;
                    }
                    

                    count++;
                    
                }    
                count=0;
                while(count<=brUzoraka){
                    
                    razX=Math.abs(du1-du2)/brUzoraka;
                    razY=Math.abs(si1-si2)/brUzoraka;
                    razT=duljinaTrase/brUzoraka;
                    rez=dat.getElevationFor(du1+(razX*count), si1+(razY*count));

                    dista1=Math.abs(distance(du1,si1,du1+(razX*count),si1+(razY*count)));
                    dista2=Math.abs(distance(du2,si2,du1+(razX*count),si1+(razY*count)));
                    fresnel=1000*Math.sqrt((dista1*dista2*(lambda/1000))/(udaljenost));//fresnel radius 

                    rez1=rezPoc+(count*rezLos/brUzoraka);
                    fresnelPlot=-Math.sqrt(dista1*dista1+fresnel*fresnel)-Math.sqrt(dista2*dista2+fresnel*fresnel)-udaljenost+rez1; //krivulja
                    if(0.1*(maxFres+rez)>fresnelPlot){
                        broj++;
                    }
                    //System.out.println(broj +" "+ dista1);
                    count++;
                    
                }   
                if(broj>0){
                    jLabel11.setVisible(true);
                    jLabel12.setVisible(false);
                } else {
                    jLabel11.setVisible(false);
                    jLabel12.setVisible(true);
                }
                
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(jLabel11.isVisible()){
            if(jLabel13.isVisible()){
                //JOptionPane.showMessageDialog(rootPane, "Linear Interpolation!");
                jLabel16.setVisible(true);
                jLabel15.setVisible(false);
                jInternalFrame1.updateUI();
            }
            else {
                //JOptionPane.showMessageDialog(rootPane, "Diffraction over the horizon!");
                
                jLabel15.setVisible(true);
                jLabel16.setVisible(false);
                jInternalFrame1.updateUI();
            }
        }

        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            String duz1=jTextField1.getText();
            String sir1=jTextField2.getText();
            String duz2=jTextField3.getText();
            String sir2=jTextField4.getText();
            String v1=jTextField9.getText();
            String v2=jTextField10.getText();
            float visAnt1=Float.valueOf(v1);
            float visAnt2=Float.valueOf(v2);
            String put="C:\\Users\\vhailor\\Documents\\NetBeansProjects\\JavaApplication10\\";
            DecimalFormat f = new DecimalFormat("##");
            DecimalFormat f1 = new DecimalFormat("##.##");
            
            double du1=Double.valueOf(duz1);
            double si1=Double.valueOf(sir1);
            double du2=Double.valueOf(duz2);
            double si2=Double.valueOf(sir2);
            String d1=String.valueOf(f.format(Math.floor(du1)));
            String s1=String.valueOf(f.format(Math.floor(si1)));
            String d2=String.valueOf(f.format(Math.floor(du2)));
            String s2=String.valueOf(f.format(Math.floor(si2)));
            int brUzoraka=10000;
            double duljinaTrase=Math.abs(distance(du1,si1,du2,si2));
            
            String nazivDat="";
            nazivDat+=put+"N"+d1+"E";
            if(si1<100) nazivDat+="0";
            nazivDat+=s1+".hgt";
            //File file = new File("C:\\Users\\vhailor\\Documents\\NetBeansProjects\\JavaApplication10\\N40E014.hgt");
            File file = new File(nazivDat);
            try{
                RandomAccessFile raf = new RandomAccessFile(file, "rw");
                GetData dat=new GetData(raf);
                double rez,rezLos,rez1,rezPoc, razT;
                int count=0;
                double razX=0,razY=0;
                boolean los=true;
                rezLos=Math.abs((dat.getElevationFor(du1, si1)+visAnt1)-(dat.getElevationFor(du2, si2)+visAnt2));//razlika najmanja najvisa tocka
                rezPoc=dat.getElevationFor(du1, si1)+visAnt1;//pocetna tocka sa uracunatom visinom antene
                    ArrayList lista1=new ArrayList();
                    ArrayList lista2=new ArrayList();
                    ArrayList lista3=new ArrayList();
                    Iterator it=lista1.iterator();
                    Iterator it1=lista2.iterator();
                    Iterator it2=lista3.iterator();
                while(count<=brUzoraka){
                    
                    razX=Math.abs(du1-du2)/brUzoraka;
                    razY=Math.abs(si1-si2)/brUzoraka;
                    razT=duljinaTrase/brUzoraka;
                    rez=dat.getElevationFor(du1+(razX*count), si1+(razY*count));
                    rez1=rezPoc+(count*rezLos/brUzoraka);
                    lista1.add(rez);
                    lista2.add(count*razT);
                    lista3.add(rez1);
                    count++;
                    
                }
                

                Ploter plot1 = new Ploter(lista2, lista1);

                RefineryUtilities.centerFrameOnScreen(plot1);                
                plot1.pack();
                plot1.setVisible(true);
                
                PlotLos plot2=new PlotLos(lista2, lista3);
                RefineryUtilities.centerFrameOnScreen(plot2);                
                plot2.pack();
                plot2.setVisible(true);
              
                
         
                


            }
            catch(IOException e){
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            String duz1=jTextField1.getText();
            String sir1=jTextField2.getText();
            String duz2=jTextField3.getText();
            String sir2=jTextField4.getText();
            String v1=jTextField9.getText();
            String v2=jTextField10.getText();
            float visAnt1=Float.valueOf(v1);
            float visAnt2=Float.valueOf(v2);
            String put="C:\\Users\\vhailor\\Documents\\NetBeansProjects\\JavaApplication10\\";
            DecimalFormat f = new DecimalFormat("##");
            DecimalFormat f1 = new DecimalFormat("##.##");
            
            double du1=Double.valueOf(duz1);
            double si1=Double.valueOf(sir1);
            double du2=Double.valueOf(duz2);
            double si2=Double.valueOf(sir2);
            String d1=String.valueOf(f.format(Math.floor(du1)));
            String s1=String.valueOf(f.format(Math.floor(si1)));
            String d2=String.valueOf(f.format(Math.floor(du2)));
            String s2=String.valueOf(f.format(Math.floor(si2)));
            
            double duljinaTrase=Math.abs(distance(du1,si1,du2,si2));
            int brUzoraka=10000;
            String nazivDat="";
            nazivDat+=put+"N"+d1+"E";
            if(si1<100) nazivDat+="0";
            nazivDat+=s1+".hgt";
            //File file = new File("C:\\Users\\vhailor\\Documents\\NetBeansProjects\\JavaApplication10\\N40E014.hgt");
            File file = new File(nazivDat);
            try{
                RandomAccessFile raf = new RandomAccessFile(file, "rw");
                GetData dat=new GetData(raf);
                double rez,rezLos,rez1,rezPoc, razT;
                int count=0;
                double razX=0,razY=0;
                boolean los=true;
                rezLos=Math.abs((dat.getElevationFor(du1, si1)+visAnt1)-(dat.getElevationFor(du2, si2)+visAnt2));//razlika najmanja najvisa tocka
                rezPoc=dat.getElevationFor(du1, si1)+visAnt1;
                    ArrayList lista1=new ArrayList();
                    ArrayList lista2=new ArrayList();
                    ArrayList lista3=new ArrayList();
                    Iterator it=lista1.iterator();
                    Iterator it1=lista2.iterator();
                    Iterator it2=lista3.iterator();
                while(count<=brUzoraka){
                    
                    razX=Math.abs(du1-du2)/brUzoraka;
                    razY=Math.abs(si1-si2)/brUzoraka;
                    razT=duljinaTrase/brUzoraka;
                    rez=dat.getElevationFor(du1+(razX*count), si1+(razY*count));
                    rez1=rezPoc+(count*rezLos/brUzoraka);
                    lista1.add(rez);
                    lista2.add(count*razT);
                    lista3.add(rez1);
                    count++;
                    
                }
                

                Export1 data = new Export1("C:/Users/vhailor/Desktop/export1.csv", true);
                data.writeToFile(lista2, lista1);
                
                JOptionPane.showMessageDialog(rootPane, "Export zavrsen!");
                
                
                


            }
            catch(IOException e){
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            String frek=jTextField8.getText();
            String put="C:\\Users\\vhailor\\Documents\\NetBeansProjects\\JavaApplication10\\";
            DecimalFormat f = new DecimalFormat("##");
            DecimalFormat f1 = new DecimalFormat("##.##");
            String duz1=jTextField1.getText();
            String sir1=jTextField2.getText();
            String duz2=jTextField3.getText();
            String sir2=jTextField4.getText();
            String v1=jTextField9.getText();
            String v2=jTextField10.getText();
            float visAnt1=Float.valueOf(v1);
            float visAnt2=Float.valueOf(v2);
            double du1=Double.valueOf(duz1);
            double si1=Double.valueOf(sir1);
            double du2=Double.valueOf(duz2);
            double si2=Double.valueOf(sir2);
            float antVis1=Float.valueOf(jTextField9.getText());
            float antVis2=Float.valueOf(jTextField10.getText());
            String d1=String.valueOf(f.format(Math.floor(du1)));
            String s1=String.valueOf(f.format(Math.floor(si1)));
            String d2=String.valueOf(f.format(Math.floor(du2)));
            String s2=String.valueOf(f.format(Math.floor(si2)));
            int brUzoraka=10000;
            double duljinaTrase=Math.abs(distance(du1,si1,du2,si2));
            String nazivDat="";
            nazivDat+=put+"N"+d1+"E";
            if(si1<100) nazivDat+="0";
            nazivDat+=s1+".hgt";
            //File file = new File("C:\\Users\\vhailor\\Documents\\NetBeansProjects\\JavaApplication10\\N40E014.hgt");
            File file = new File(nazivDat);
            try{
                RandomAccessFile raf = new RandomAccessFile(file, "rw");
                GetData dat=new GetData(raf);
                int broj=0;
                double udaljenost=Math.abs(distance(du1,si1,du2,si2));
                double max=0;//MAX fresnel
                double maxPrep=0;
                double fresnel;
                double rez,rezLos,rez1,rezPoc;
                int count=0;
                double razX=0,razY=0,razT;
                double dista1,dista2;
                double fresnelPlot;
                double lambda=0.3/Double.parseDouble(frek);//frek u GHz --> lambda u m !!!!!!!!!!!
                
                rezPoc=dat.getElevationFor(du1, si1)+visAnt1;
                rezLos=Math.abs((dat.getElevationFor(du1, si1)+visAnt1)-(dat.getElevationFor(du2, si2)+visAnt2));
                ArrayList lista3=new ArrayList();
                ArrayList lista4=new ArrayList();
                Iterator i3=lista3.iterator();
                Iterator i4= lista4.iterator();
                while(count<brUzoraka){
                    
                    razX=Math.abs(du1-du2)/brUzoraka;
                    razY=Math.abs(si1-si2)/brUzoraka;
                    razT=duljinaTrase/brUzoraka;
                    rez=dat.getElevationFor(du1+(razX*count), si1+(razY*count));

                    dista1=Math.abs(distance(du1,si1,du1+(razX*count),si1+(razY*count)));
                    dista2=Math.abs(distance(du2,si2,du1+(razX*count),si1+(razY*count)));
                    rez1=rezPoc+(count*rezLos/brUzoraka);
                    fresnel=1000*Math.sqrt((dista1*dista2*(lambda/1000))/(udaljenost));//fresnel radius u metrima
                    fresnelPlot=-Math.sqrt(dista1*dista1+fresnel*fresnel)-Math.sqrt(dista2*dista2+fresnel*fresnel)-udaljenost+rez1;
                    lista3.add(fresnelPlot);
                    lista4.add(count*razT);
                    
                    count++;
        
                    
                }    
                PlotFresnel p1 = new PlotFresnel(lista4, lista3);
                RefineryUtilities.centerFrameOnScreen(p1);                
                p1.pack();
                p1.setVisible(true);
                
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(1);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
            String duz1=jTextField1.getText();
            String sir1=jTextField2.getText();
            String duz2=jTextField3.getText();
            String sir2=jTextField4.getText();
            String v1=jTextField9.getText();
            String v2=jTextField10.getText();
            float visAnt1=Float.valueOf(v1);
            float visAnt2=Float.valueOf(v2);
            String put="C:\\Users\\vhailor\\Documents\\NetBeansProjects\\JavaApplication10\\";
            DecimalFormat f = new DecimalFormat("##");
            DecimalFormat f1 = new DecimalFormat("##.##");
            
            double du1=Double.valueOf(duz1);
            double si1=Double.valueOf(sir1);
            double du2=Double.valueOf(duz2);
            double si2=Double.valueOf(sir2);
            String d1=String.valueOf(f.format(Math.floor(du1)));
            String s1=String.valueOf(f.format(Math.floor(si1)));
            String d2=String.valueOf(f.format(Math.floor(du2)));
            String s2=String.valueOf(f.format(Math.floor(si2)));
            
            double duljinaTrase=Math.abs(distance(du1,si1,du2,si2));
            int brUzoraka=10000;
            String nazivDat="";
            nazivDat+=put+"N"+d1+"E";
            if(si1<100) nazivDat+="0";
            nazivDat+=s1+".hgt";
            //File file = new File("C:\\Users\\vhailor\\Documents\\NetBeansProjects\\JavaApplication10\\N40E014.hgt");
            File file = new File(nazivDat);
            try{
                RandomAccessFile raf = new RandomAccessFile(file, "rw");
                GetData dat=new GetData(raf);
                double rez,rezLos,rez1,rezPoc, razT;
                int count=0;
                double razX=0,razY=0;
                boolean los=true;
                rezLos=Math.abs((dat.getElevationFor(du1, si1)+visAnt1)-(dat.getElevationFor(du2, si2)+visAnt2));//razlika najmanja najvisa tocka
                rezPoc=dat.getElevationFor(du1, si1)+visAnt1;
                    ArrayList lista1=new ArrayList();
                    ArrayList lista2=new ArrayList();
                    ArrayList lista3=new ArrayList();
                    Iterator it=lista1.iterator();
                    Iterator it1=lista2.iterator();
                    Iterator it2=lista3.iterator();
                while(count<=brUzoraka){
                    
                    razX=Math.abs(du1-du2)/brUzoraka;
                    razY=Math.abs(si1-si2)/brUzoraka;
                    razT=duljinaTrase/brUzoraka;
                    rez=dat.getElevationFor(du1+(razX*count), si1+(razY*count));
                    rez1=rezPoc+(count*rezLos/brUzoraka);
                    lista1.add(rez);
                    lista2.add(count*razT);
                    lista3.add(rez1);
                    count++;
                    
                }
                

                Export1 data = new Export1("C:/Users/vhailor/Desktop/export1.csv", true);
                data.writeToFile(lista2, lista1);
                
                JOptionPane.showMessageDialog(rootPane, "Export zavrsen!");
                
                
                


            }
            catch(IOException e){
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
            String frek=jTextField8.getText();
            String put="C:\\Users\\vhailor\\Documents\\NetBeansProjects\\JavaApplication10\\";
            DecimalFormat f = new DecimalFormat("##");
            DecimalFormat f1 = new DecimalFormat("##.##");
            String duz1=jTextField1.getText();
            String sir1=jTextField2.getText();
            String duz2=jTextField3.getText();
            String sir2=jTextField4.getText();
            String v1=jTextField9.getText();
            String v2=jTextField10.getText();
            float visAnt1=Float.valueOf(v1);
            float visAnt2=Float.valueOf(v2);
            double du1=Double.valueOf(duz1);
            double si1=Double.valueOf(sir1);
            double du2=Double.valueOf(duz2);
            double si2=Double.valueOf(sir2);
            float antVis1=Float.valueOf(jTextField9.getText());
            float antVis2=Float.valueOf(jTextField10.getText());
            String d1=String.valueOf(f.format(Math.floor(du1)));
            String s1=String.valueOf(f.format(Math.floor(si1)));
            String d2=String.valueOf(f.format(Math.floor(du2)));
            String s2=String.valueOf(f.format(Math.floor(si2)));
            int brUzoraka=10000;
            double duljinaTrase=Math.abs(distance(du1,si1,du2,si2));
            String nazivDat="";
            nazivDat+=put+"N"+d1+"E";
            if(si1<100) nazivDat+="0";
            nazivDat+=s1+".hgt";
            //File file = new File("C:\\Users\\vhailor\\Documents\\NetBeansProjects\\JavaApplication10\\N40E014.hgt");
            File file = new File(nazivDat);
            try{
                RandomAccessFile raf = new RandomAccessFile(file, "rw");
                GetData dat=new GetData(raf);
                int broj=0;
                double udaljenost=Math.abs(distance(du1,si1,du2,si2));
                double max=0;//MAX fresnel
                double maxPrep=0;
                double fresnel;
                double rez,rezLos,rez1,rezPoc;
                int count=0;
                double razX=0,razY=0,razT;
                double dista1,dista2;
                double fresnelPlot;
                double lambda=0.3/Double.parseDouble(frek);//frek u GHz --> lambda u m !!!!!!!!!!!
                
                rezPoc=dat.getElevationFor(du1, si1)+visAnt1;
                rezLos=Math.abs((dat.getElevationFor(du1, si1)+visAnt1)-(dat.getElevationFor(du2, si2)+visAnt2));
                ArrayList lista3=new ArrayList();
                ArrayList lista4=new ArrayList();
                Iterator i3=lista3.iterator();
                Iterator i4= lista4.iterator();
                while(count<brUzoraka){
                    
                    razX=Math.abs(du1-du2)/brUzoraka;
                    razY=Math.abs(si1-si2)/brUzoraka;
                    razT=duljinaTrase/brUzoraka;
                    rez=dat.getElevationFor(du1+(razX*count), si1+(razY*count));

                    dista1=Math.abs(distance(du1,si1,du1+(razX*count),si1+(razY*count)));
                    dista2=Math.abs(distance(du2,si2,du1+(razX*count),si1+(razY*count)));
                    rez1=rezPoc+(count*rezLos/brUzoraka);
                    fresnel=1000*Math.sqrt((dista1*dista2*(lambda/1000))/(udaljenost));//fresnel radius u metrima
                    fresnelPlot=-Math.sqrt(dista1*dista1+fresnel*fresnel)-Math.sqrt(dista2*dista2+fresnel*fresnel)-udaljenost+rez1;
                    lista3.add(fresnelPlot);
                    lista4.add(count*razT);
                    
                    count++;
        
                    
                }  
                

                Export2 data = new Export2("C:/Users/vhailor/Desktop/export2.csv", true);
                data.writeToFile(lista4, lista3);
                
                JOptionPane.showMessageDialog(rootPane, "Export zavrsen!");
                
                
                


            }
            catch(IOException e){
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
            String frek=jTextField8.getText();
            String put="C:\\Users\\vhailor\\Documents\\NetBeansProjects\\JavaApplication10\\";
            DecimalFormat f = new DecimalFormat("##");
            DecimalFormat f1 = new DecimalFormat("##.##");
            String duz1=jTextField1.getText();
            String sir1=jTextField2.getText();
            String duz2=jTextField3.getText();
            String sir2=jTextField4.getText();
            String v1=jTextField9.getText();
            String v2=jTextField10.getText();
            float visAnt1=Float.valueOf(v1);
            float visAnt2=Float.valueOf(v2);
            double du1=Double.valueOf(duz1);
            double si1=Double.valueOf(sir1);
            double du2=Double.valueOf(duz2);
            double si2=Double.valueOf(sir2);
            float antVis1=Float.valueOf(jTextField9.getText());
            float antVis2=Float.valueOf(jTextField10.getText());
            String d1=String.valueOf(f.format(Math.floor(du1)));
            String s1=String.valueOf(f.format(Math.floor(si1)));
            String d2=String.valueOf(f.format(Math.floor(du2)));
            String s2=String.valueOf(f.format(Math.floor(si2)));
            int brUzoraka=10000;
            double duljinaTrase=Math.abs(distance(du1,si1,du2,si2));
            String nazivDat="";
            nazivDat+=put+"N"+d1+"E";
            if(si1<100) nazivDat+="0";
            nazivDat+=s1+".hgt";
            //File file = new File("C:\\Users\\vhailor\\Documents\\NetBeansProjects\\JavaApplication10\\N40E014.hgt");
            File file = new File(nazivDat);
            try{
                RandomAccessFile raf = new RandomAccessFile(file, "rw");
                GetData dat=new GetData(raf);
                int broj=0;
                double udaljenost=Math.abs(distance(du1,si1,du2,si2));
                double max=0;//MAX fresnel
                double maxPrep=0;
                double fresnel;
                double rez,rezLos,rez1,rezPoc;
                int count=0;
                double razX=0,razY=0,razT;
                double dista1,dista2;
                double fresnelPlot;
                double lambda=0.3/Double.parseDouble(frek);//frek u GHz --> lambda u m !!!!!!!!!!!
                
                rezPoc=dat.getElevationFor(du1, si1)+visAnt1;
                rezLos=Math.abs((dat.getElevationFor(du1, si1)+visAnt1)-(dat.getElevationFor(du2, si2)+visAnt2));
                ArrayList lista3=new ArrayList();
                ArrayList lista4=new ArrayList();
                Iterator i3=lista3.iterator();
                Iterator i4= lista4.iterator();
                while(count<brUzoraka){
                    
                    razX=Math.abs(du1-du2)/brUzoraka;
                    razY=Math.abs(si1-si2)/brUzoraka;
                    razT=duljinaTrase/brUzoraka;
                    rez=dat.getElevationFor(du1+(razX*count), si1+(razY*count));

                    dista1=Math.abs(distance(du1,si1,du1+(razX*count),si1+(razY*count)));
                    dista2=Math.abs(distance(du2,si2,du1+(razX*count),si1+(razY*count)));
                    rez1=rezPoc+(count*rezLos/brUzoraka);
                    fresnel=1000*Math.sqrt((dista1*dista2*(lambda/1000))/(udaljenost));//fresnel radius u metrima
                    fresnelPlot=-Math.sqrt(dista1*dista1+fresnel*fresnel)-Math.sqrt(dista2*dista2+fresnel*fresnel)-udaljenost+rez1;
                    lista3.add(fresnelPlot);
                    lista4.add(count*razT);
                    
                    count++;
        
                    
                }  
                

                Export2 data = new Export2("C:/Users/vhailor/Desktop/export2.csv", true);
                data.writeToFile(lista4, lista3);
                
                JOptionPane.showMessageDialog(rootPane, "Export zavrsen!");
                
                
                


            }
            catch(IOException e){
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Karta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Karta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Karta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Karta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Karta().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
